# Generated by Django 2.0.1 on 2018-04-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktickets', '0003_auto_20180403_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatallocation',
            name='show',
        ),
        migrations.RemoveField(
            model_name='showmovie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='showmovie',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='SeatAllocation',
        ),
        migrations.DeleteModel(
            name='ShowMovie',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
    ]
