# Generated by Django 2.0.1 on 2018-04-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktickets', '0006_auto_20180403_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_list', to='booktickets.Movie'),
        ),
    ]
