# Generated by Django 2.0.1 on 2018-04-04 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booktickets', '0010_auto_20180404_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=60)),
                ('director', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('audi_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Screen_no', models.IntegerField()),
                ('row_name', models.CharField(max_length=6)),
                ('no_of_seats', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowMovie',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('theatre_name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_list', to='booktickets.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='showmovie',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre', to='booktickets.Theatre'),
        ),
        migrations.AddField(
            model_name='seatallocation',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktickets.ShowMovie'),
        ),
    ]
