# Generated by Django 2.0.1 on 2018-04-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktickets', '0011_auto_20180404_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showmovie',
            name='show_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
