# Generated by Django 2.0.1 on 2018-04-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktickets', '0012_auto_20180404_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatallocation',
            old_name='show',
            new_name='shows',
        ),
    ]
