# Generated by Django 2.0.1 on 2018-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktickets', '0015_auto_20180404_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showmovie',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
