# Generated by Django 2.0.1 on 2018-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktickets', '0017_auto_20180404_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showmovie',
            name='date',
            field=models.DateField(),
        ),
    ]
