# Generated by Django 2.0.1 on 2018-04-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktickets', '0022_theatre_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre_map',
            name='date',
        ),
        migrations.RemoveField(
            model_name='theatre_map',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='Theatre_Map',
        ),
    ]
