# Generated by Django 2.0.1 on 2018-04-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktickets', '0024_theatre_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatallocation',
            name='show',
        ),
        migrations.RemoveField(
            model_name='showmovie',
            name='theatre',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='theatre_map',
            name='date',
        ),
        migrations.RemoveField(
            model_name='theatre_map',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='SeatAllocation',
        ),
        migrations.DeleteModel(
            name='ShowMovie',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
        migrations.DeleteModel(
            name='Theatre_Map',
        ),
    ]
