# Generated by Django 2.0.1 on 2018-04-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booktickets', '0025_auto_20180405_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=60)),
                ('director', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='booktickets.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('theatre_name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema', to='booktickets.Theatre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre', to='booktickets.Theatre'),
        ),
        migrations.AddField(
            model_name='c_city',
            name='city_id',
            field=models.ForeignKey(on_delete='true', related_name='city', to='booktickets.City'),
        ),
        migrations.AddField(
            model_name='c_city',
            name='theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre1', to='booktickets.Theatre'),
        ),
    ]
