# Generated by Django 2.0.1 on 2018-04-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktickets', '0026_auto_20180405_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='theatre_id',
            new_name='theatre',
        ),
    ]
