# Generated by Django 2.0.1 on 2018-04-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomerRegistration',
        ),
    ]
