# Generated by Django 2.0.1 on 2018-04-02 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0002_auto_20180402_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('states', models.CharField(choices=[('Rajasthan', 'Rajashan'), ('Gujarat', 'Gujarat'), ('Maharashtra', 'Maharashtra'), ('UttarPradesh', 'UttarPradesh'), ('Karnataka', 'Karnataka'), ('Delhi', 'Delhi')], max_length=20)),
                ('city', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Vadodara', 'Vadodara'), ('Jaipur', 'Jaipur'), ('Udaipur', 'Udaipur'), ('Pune', 'Pune'), ('Bombay', 'Bombay'), ('Noida', 'Noida'), ('Banglore', 'Banglore')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
